services:
  - type: web
    name: cats-flats-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run build
    startCommand: |
      API_PORT=$PORT npm run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: MEDIA_STORAGE_ROOT
        value: /tmp/uploads
      - key: MEDIA_PUBLIC_PATH
        value: /uploads
      - key: MEDIA_BASE_URL
        value: https://cats-flats-api.onrender.com/uploads
      - key: NEXT_PUBLIC_API_BASE_URL
        sync: false

  - type: web
    name: cats-flats-web
    env: node
    plan: free
    buildCommand: |
      npm --prefix apps/web install
      npm --prefix apps/web run build
    startCommand: |
      NEXT_PUBLIC_API_BASE_URL=https://cats-flats-api.onrender.com npm --prefix apps/web run start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
